# Generated by Django 6.0.3 on 2026-04-01 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(max_length=12, unique=True, verbose_name="RUT"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre completo"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, null=True, upload_to="perfiles/"),
                ),
                ("face_encoding", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mensualidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activa", models.BooleanField(default=False)),
                ("fecha_vencimiento", models.DateField()),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensualidad",
                        to="acceso.usuario",
                    ),
                ),
            ],
        ),
    ]
