# Generated by Django 6.0.3 on 2026-04-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador (Acceso Total)"),
                    ("RECEPCION", "Recepcionista (Ventas y Registros)"),
                    ("ENTRENADOR", "Entrenador (Clases y Alumnos)"),
                    ("CLIENTE", "Cliente (Perfil y Pagos)"),
                ],
                default="CLIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_nacimiento",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_perfil/"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rut",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="acceso.usuario",
                    ),
                ),
            ],
        ),
    ]
