# Generated by Django 6.0.3 on 2026-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0002_usuario_rol_alter_usuario_fecha_nacimiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
