# Generated by Django 6.0.3 on 2026-04-06 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0003_usuario_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("grupo_muscular", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RutinaCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia_nombre", models.CharField(max_length=50)),
                ("series", models.IntegerField(default=4)),
                ("repeticiones", models.CharField(max_length=20)),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceso.ejercicio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutinas",
                        to="acceso.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgresoRutina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "peso_levantado",
                    models.DecimalField(
                        decimal_places=2, help_text="Peso en KG", max_digits=5
                    ),
                ),
                ("completado", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acceso.usuario"
                    ),
                ),
                (
                    "rutina_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acceso.rutinacliente",
                    ),
                ),
            ],
        ),
    ]
