# Generated by Django 6.0.3 on 2026-04-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0004_ejercicio_rutinacliente_progresorutina"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensualidad",
            name="tipo_plan",
            field=models.CharField(
                choices=[
                    ("BASICA", "Suscripción Básica ($25.000 / mes)"),
                    ("VIDA_SANA", "Suscripción Vida Sana ($30.000 / mes)"),
                    ("RENDIMIENTO", "Suscripción Rendimiento ($40.000 / mes)"),
                ],
                default="BASICA",
                max_length=20,
            ),
        ),
    ]
